blueprint:
  name: Aktywne powiadomienia na Androida po wejściu do strefy
  description: Powiadomienie.
  domain: automation
  input:
    notify_device:
      name: Urządzenie do powiadomienia
      description: Urządzenie musi mieć zainstalowaną oficjalną aplikację Home Assistant, aby otrzymywać powiadomienia
      selector:
        device:
          integration: mobile_app
    trigger_entity:
      name: Encja wyzwalająca
      description: Encja, która wywoła powiadomienie
      selector:
        entity:
          domain: person
    trigger_event:
      name: Zdarzenie wyzwalające
      description: Wybierz, czy powiadomienie ma być aktywowane przez wejście czy opuszczenie strefy
      selector:
        select:
          options:
          - opuszczenie
          - wejście
    trigger_zone:
      name: Strefa wyzwalająca
      description: Wybierz strefę używaną do wyzwalania
      selector:
        entity:
          domain: zone
    notification_title:
      name: Tytuł powiadomienia (opcjonalnie)
      description: Tytuł powiadomienia
      default: ''
    notification_message:
      name: Wiadomość z powiadomieniem (opcjonalnie)
      description: Treść powiadomienia
      default: ''
    persistent_notification:
      name: Utworzyć trwałe powiadomienie?
      description: Powiadomień trwałych nie można wyłączyć, przesuwając palcem
      default: false
      selector:
        boolean: {}
    action_1_title:
      name: Nazwa pierwszej akcji
      description: Nazwa pierwszego przycisku
      default: ''
    action_1_uri:
      name: Identyfikator URI akcji 1 (opcjonalnie)
      description: Opcjonalny identyfikator URI dla pierwszej akcji
      default: ''
    first_action:
      name: Akcja 1
      description: "Akcja do uruchomienia po kliknięciu pierwszej akcji"
      default: []
      selector:
        action: {}
    action_2_title:
      name: Nazwa drugiej akcji
      description: Nazwa drugiego przycisku
      default: ''
    action_2_uri:
      name: Identyfikator URI akcji 2 (opcjonalnie)
      description: Opcjonalny identyfikator URI dla drugiej akcji
      default: ''
    second_action:
      name: Akcja 2
      description: "Akcja do uruchomienia po kliknięciu drugiej akcji"
      default: []
      selector:
        action: {}
    action_3_title:
      name: Nazwa trzeciej akcji
      description: Nazwa trzeciego przycisku
      default: ''
    action_3_uri:
      name: Identyfikator URI akcji 3 (opcjonalnie)
      description: Opcjonalny identyfikator URI dla trzeciej akcji
      default: ''
    third_action:
      name: Akcja 3
      description: "Akcja do uruchomienia po kliknięciu trzeciej akcji"
      default: []
      selector:
        action: {}
  source_url: https://community.home-assistant.io/t/actionable-notifications-for-android-when-entering-or-leaving-a-zone/303508
mode: restart
max_exceeded: silent
variables:
  notify_device: !input 'notify_device'
  trigger_entity: !input 'trigger_entity'
  trigger_event: !input 'trigger_event'
  trigger_zone: !input 'trigger_zone'
  notification_title: !input 'notification_title'
  notification_message: !input 'notification_message'
  persistent_notification: !input 'persistent_notification'
  action_1_title: !input 'action_1_title'
  action_1_uri: !input 'action_1_uri'
  first_action: !input 'first_action'
  action_2_title: !input 'action_2_title'
  action_2_uri: !input 'action_2_uri'
  second_action: !input 'second_action'
  action_3_title: !input 'action_3_title'
  action_3_uri: !input 'action_3_uri'
  third_action: !input 'third_action'
trigger:
- platform: zone
  entity_id: !input 'trigger_entity'
  zone: !input 'trigger_zone'
  event: !input 'trigger_event'
action:
- domain: mobile_app
  type: notify
  device_id: !input 'notify_device'
  title: '{{ notification_title }}'
  message: '{{ notification_message }}'
  data:
    tag: '{{ notification_title }}'
    persistent: '{{ persistent_notification }}'
    actions: "{% set titles = [action_1_title, action_2_title, action_3_title] %}\
      \ {% set uris = [action_1_uri, action_2_uri, action_3_uri] %} {% set actions\
      \ = namespace(data = []) %}\n{% for title in titles %}\n  {% if title|length\
      \ %}\n    {% set uri = uris[loop.index - 1] %}\n    {% set action_name = \"\
      action\" + loop.index|string %}\n    {% set action = {\n      \"action\": \"\
      URI\" if uri|length else action_name,\n      \"title\": title,\n      \"uri\"\
      : uri \n      }\n    %}\n    {% set actions.data = actions.data + [action] %}\n\
      \  {% endif %}\n{% endfor %} {{ actions.data }}\n"
- wait_for_trigger:
    platform: event
    event_type: mobile_app_notification_action
- choose:
  - conditions: '{{ wait.trigger.event.data.action == ''action1'' }}'
    sequence: !input 'first_action'
  - conditions: '{{ wait.trigger.event.data.action == ''action2'' }}'
    sequence: !input 'second_action'
  - conditions: '{{ wait.trigger.event.data.action == ''action3'' }}'
    sequence: !input 'third_action'
