blueprint:
  name: Wstrzymaj mediaplayer podczas rozmowy telefonicznej.
  description: >
    Wstrzymaj odtwarzacz multimedialny, gdy telefon dzwoni.
    Tylko wtedy, gdy osoba jest w domu, a odtwarzacz multimedialny odtwarza.
  domain: automation
  input:
    phone_state:
      name: Czujnik stanu telefonu
      description: Wszystkie czujniki tworzone przez aplikację mobilną. Tutaj wybierz czujnik stanu telefonu.
      selector:
        entity:
          integration: mobile_app
          domain: sensor
    person:
      name: Osoba
      description: Wybierz osobę, która musi znajdować się w wybranej strefie.
      selector:
        entity:
          domain: person
    zone:
      name: Strefa
      description: Wybierz strefę, w której dana osoba ma się znajdować.
      default: zone.home
      selector:
          entity:
            domain: zone
    media_player: 
      name: Odtwarzacz multimedialny
      description: Wybierz odtwarzacz multimedialny, który ma zostać wstrzymany.
      selector:
        entity:
          domain: media_player

trigger:
  - platform: state
    entity_id: !input phone_state
    to: "ringing"
  - platform: state
    entity_id: !input phone_state
    to: "offhook"
variables: 
  zone: !input zone
  zone_name: "{{ zone[5:] }}"
  entity: !input person
condition:
  - "{{is_state(entity, zone_name)}}"
  - condition: state
    entity_id: !input media_player
    state: playing
action:
  - service: media_player.media_pause
    entity_id: !input media_player
  - wait_for_trigger:
    - platform: state 
      entity_id: !input phone_state
      to: "idle" 
    timeout:
      seconds: 300
  - service: media_player.media_play
    entity_id: !input media_player
